# Generated by Django 4.0.5 on 2022-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBazarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('instagram', models.CharField(max_length=30, verbose_name='Instagram')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Servicio')),
            ],
        ),
    ]
