# Generated by Django 4.0.5 on 2022-07-23 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoBazarApp', '0002_nosotros_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name_plural': 'Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name_plural': 'Servicios'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
